version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tfm-app
    environment:
      - PYTHONPATH=/home/app/src
    volumes:
      - .:/home/app
    ports:
      - "8888:8888"
    networks:
      - tfm-network
    tty: true
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --allow-root
      --notebook-dir=/home/app/notebooks

  mongo:
    image: mongo:7.0
    container_name: tfm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tfm-network

  mongo-express:
    image: mongo-express:1.0
    container_name: tfm-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - tfm-network

networks:
  tfm-network:
    driver: bridge

volumes:
  mongo-data: