version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tfm-app
    volumes:
      - ./src:/home/app/src
    networks:
      - tfm-network
    tty: true

  mongo:
    image: mongo:7.0
    container_name: tfm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tfm-network

  mongo-express:
    image: mongo-express:1.0
    container_name: tfm-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - tfm-network

networks:
  tfm-network:
    driver: bridge

volumes:
  mongo-data: